name: Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
          - os: macos
            arch: arm64
          - os: macos
            arch: amd64  

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - run: |
        npm i
        npm run build
        npm run pack
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}
        path: |
          release/**/*.dmg
          release/**/*.exe
          release/**/*-lates*.yml
          !release/**/win-unpacked/
